export enum ButtonEnum
{
	START = 'BUTTON_START',
	NEW = 'BUTTON_NEW',
	FORGET_GOAL = 'BUTTON_FORGET_GOAL',
	FORGET_CONFIRM = 'BUTTON_FORGET_CONFIRM',
	YES_SUCCESS = 'YES_SUCCESS',
	NO_FAILED = 'NO_FAILED',
}